-- =============================================================================
-- 0001_enrichment_provenance.sql — make gov_postgres the single source of
--                                  truth for Nia's bill enrichments.
-- =============================================================================
-- Applied: paste this whole file into psql against the live gov_postgres.
--   docker exec -i gov_postgres psql -U blacksky -d whoisourgov \
--     < oracle-stack/migrations/0001_enrichment_provenance.sql
--
-- Why this exists:
--   `bills` already has a `plain_english` column waiting for Maurice/Nia
--   to fill. Until now Nia generated summaries into her own local `nia.db`
--   — a parallel store. The new architecture makes `gov_postgres` the
--   canonical home: Nia writes summaries here, the Supabase bridge picks
--   them up automatically (it already passes `plain_english` through),
--   and Scrollvate's bill cards inherit the richer copy on the next
--   daily rebuild. Nia's nia.db becomes a working cache, not a parallel
--   universe.
--
-- What this migration does:
--   1. Adds enrichment-provenance columns alongside `plain_english`.
--   2. Adds two derived helpers (`impact_summary`, `enrichment_version`).
--   3. Indexes on `plain_english_written_at` for "what's stale" queries.
--   4. Provisions a read-write role `nia_writer` with INSERT/UPDATE
--      privileges *only* on the enrichment columns — never on
--      structural fields like `external_id`, `status`, `sponsor_id`.
--
-- All statements are IF NOT EXISTS / IF EXISTS guarded; safe to re-run.
-- =============================================================================

-- ── Provenance columns ────────────────────────────────────────────────────
ALTER TABLE bills
  -- Which LLM wrote the current summary. e.g. 'meta-llama-3.1-8b-instruct-turbo',
  -- 'claude-haiku-4-5-20251001'. NULL until first enrichment runs.
  ADD COLUMN IF NOT EXISTS plain_english_model       TEXT,

  -- When Nia last wrote a summary for this row.
  ADD COLUMN IF NOT EXISTS plain_english_written_at  TIMESTAMPTZ,

  -- Schema-version tag bumped when the enrichment prompt / output
  -- contract changes materially. Lets us invalidate stale summaries
  -- without dropping the column.
  ADD COLUMN IF NOT EXISTS enrichment_version        TEXT,

  -- Optional richer fields. plain_english is the one-liner ("what this
  -- bill does"). impact_summary is "who does it affect and how" —
  -- 1-2 sentences, also generated by Nia in the same call.
  ADD COLUMN IF NOT EXISTS impact_summary            TEXT;

-- ── Indexes ──────────────────────────────────────────────────────────────
-- "Which bills do I still need to summarize?" — common Nia query.
CREATE INDEX IF NOT EXISTS bills_plain_english_pending_idx
  ON bills (introduced_at DESC)
  WHERE plain_english IS NULL;

-- "When did Nia last touch each bill?" — staleness query for
-- re-enrichment after prompt bumps.
CREATE INDEX IF NOT EXISTS bills_enrichment_written_idx
  ON bills (plain_english_written_at DESC NULLS LAST)
  WHERE plain_english_written_at IS NOT NULL;

-- ── nia_writer role ──────────────────────────────────────────────────────
-- Locked down: can only SELECT + UPDATE on the enrichment columns of
-- the bills table. Cannot INSERT new rows. Cannot UPDATE structural
-- columns like external_id, status, sponsor_id. Cannot touch any other
-- table beyond SELECT.

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nia_writer') THEN
    -- Rotate this password if it ever leaks; ALTER ROLE nia_writer PASSWORD '...'
    CREATE ROLE nia_writer WITH LOGIN PASSWORD 'change-me-after-applying';
  END IF;
END$$;

GRANT CONNECT ON DATABASE whoisourgov TO nia_writer;
GRANT USAGE   ON SCHEMA   public      TO nia_writer;

-- Read every table (Nia needs to plan her work from the structural data).
GRANT SELECT ON ALL TABLES IN SCHEMA public TO nia_writer;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT ON TABLES TO nia_writer;

-- Write *only* the enrichment columns on bills. Column-scoped UPDATE
-- is the cleanest way to say "you own these four fields and nothing else."
GRANT UPDATE (plain_english,
              plain_english_model,
              plain_english_written_at,
              enrichment_version,
              impact_summary)
  ON bills TO nia_writer;

-- Explicitly deny everything else for clarity. (Postgres defaults already
-- block these for non-superuser roles, but the REVOKE makes intent
-- legible in the schema dump.)
REVOKE INSERT, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA public FROM nia_writer;

-- ── Done. ────────────────────────────────────────────────────────────────
-- Next step (operational, not SQL):
--   1. ALTER ROLE nia_writer PASSWORD '<strong-password>';
--   2. Paste the corresponding DSN into Nia's .env as NIA_WRITER_DSN:
--        NIA_WRITER_DSN=postgresql://nia_writer:<password>@10.1.10.4:5434/whoisourgov
--   3. Run scripts/enrich_bills.py from the Nia codebase.
-- =============================================================================
